name: imo_a1_funeq
num_files: 1
language: LEAN
few_shot_data_path_for_retrieval:
few_shot_metadata_filename_for_retrieval:
dfs_data_path_for_retrieval:
dfs_metadata_filename_for_retrieval:
datasets:
  - project: data/benchmarks/FunEq
    files:
      - path: src/dataset.lean
        theorems:
          - imo_2002_a1
          - imo_2019_a1
          - imo_2018_a1
          - imo_2012_a1
          - imo_2010_a1
          - imo_2008_a1
