name: imo_funeq
num_files: 1
language: LEAN
few_shot_data_path_for_retrieval:
few_shot_metadata_filename_for_retrieval:
dfs_data_path_for_retrieval:
dfs_metadata_filename_for_retrieval:
datasets:
  - project: data/benchmarks/FunEq
    files:
      - path: src/dataset.lean
        theorems:
          - imo_2022_a3
          - imo_2022_a6
          - imo_2021_a8
          - imo_2020_a8
          - imo_2019_a1
          - imo_2018_a1
          - imo_2018_a5
          - imo_2017_a6
          - imo_2017_a8
          - imo_2016_a4
          - imo_2016_a7
          - imo_2015_a2
          - imo_2015_a4
          - imo_2014_a4
          - imo_2014_a6
          - imo_2013_a3
          - imo_2013_a5
          - imo_2012_a1
          - imo_2012_a5
          - imo_2011_a3
          - imo_2011_a6
          - imo_2010_a1
          - imo_2010_a5
          - imo_2009_a7
          - imo_2008_a1
          - imo_2007_a4
          - imo_2005_a2
          - imo_2005_a4
          - imo_2004_a3
          - imo_2002_a1
          - imo_2002_a4
