name: imo_a1_2002
num_files: 1
language: LEAN
few_shot_data_path_for_retrieval:
few_shot_metadata_filename_for_retrieval:
dfs_data_path_for_retrieval:
dfs_metadata_filename_for_retrieval:
datasets:
  - project: data/benchmarks/miniF2F
    files:
      - path: lean/src/test.lean
        theorems:
          - imo_2002_a1_p1
          - imo_2002_a1_p2
          - imo_2002_a1_p3
          - imo_2002_a1_p4
          - imo_2002_a1_p5
          - imo_2002_a1_p6
