name: miniF2F_test_mathd_numbertheory_custom
num_files: 1
language: LEAN
few_shot_data_path_for_retrieval:
few_shot_metadata_filename_for_retrieval:
dfs_data_path_for_retrieval:
dfs_metadata_filename_for_retrieval:
datasets:
  - project: data/benchmarks/miniF2F
    files:
      - path: lean/src/test.lean
        theorems:
          - mathd_numbertheory_435
          - mathd_numbertheory_447
          - mathd_numbertheory_451
          - mathd_numbertheory_457
          - mathd_numbertheory_483
          - mathd_numbertheory_495
          - mathd_numbertheory_5
          - mathd_numbertheory_517
          - mathd_numbertheory_521
          - mathd_numbertheory_541
          - mathd_numbertheory_551
          - mathd_numbertheory_552
          - mathd_numbertheory_559
          - mathd_numbertheory_582
          - mathd_numbertheory_618
          - mathd_numbertheory_66
          - mathd_numbertheory_711
          - mathd_numbertheory_728
          - mathd_numbertheory_764
          - mathd_numbertheory_765
          - mathd_numbertheory_769
          - mathd_numbertheory_85
          - mathd_numbertheory_99
          - mathd_numbertheory_430
